<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>net10.0</TargetFrameworks>
	  <PackageId>XFrame.Bff</PackageId>
	  <Version>10.0.8</Version>
	  <Authors>Lwandile Mfundisi</Authors>
	  <Description>Reusable ASP.NET Core BFF for Keycloak/OpenID Connect applications.</Description>
	  <IsPackable>true</IsPackable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
	<Target DependsOnTargets="ResolveReferences" Name="CopyProjectReferencesToPackage">
		<ItemGroup>
			<BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))" />
		</ItemGroup>
	</Target>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.11" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.12" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.16" />
		<PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
	</ItemGroup>

</Project>
